workspace:
  base: /go
  path: src/github.com/metalmatze/digitalocean_exporter

pipeline:
  build:
    image: golang:alpine
    pull: true
    commands:
      - apk add -U git make
      - make fmt
      - make vet
      - make lint
      - make build
    when:
      event: [ push, tag, pull_request ]

  docker:
    image: plugins/docker
    repo: metalmatze/digitalocean_exporter
    tags: [ latest ]
    when:
      event: push
      branch: master

  docker:
    image: plugins/docker
    repo: metalmatze/digitalocean_exporter
    tags: [ '${DRONE_TAG}' ]
    when:
      event: tag

  github:
    image: plugins/github-release
    files: dist/*
    when:
      event: tag
