workspace:
  base: /go
  path: src/github.com/metalmatze/digitalocean_exporter

pipeline:
  build:
    image: golang:alpine
    pull: true
    commands:
      - apk add -U git make
      - make fmt
      - make vet
      - make lint
      - make test
      - make build
    when:
      event: [ push, tag, pull_request ]

  release:
    image: golang:alpine
    commands:
      - apk add -U git make
      - make release
    when:
      event: tag

  docker:
    image: plugins/docker
    repo: metalmatze/digitalocean_exporter
    secrets: [ docker_username, docker_password ]
    tag: [ 0.5 ]
    when:
      event: tag

  github:
    image: plugins/github-release
    secrets: [ github_token ]
    files: dist/*
    when:
      event: tag
